spring.application.name=api-biblioteca

server.port=8080
server.servlet.context-path=/

spring.jackson.default-property-inclusion=non_null

logging.level.catolica.edu.sv.api_biblioteca=INFO

scalar.enabled=true
scalar.url=/openapi.json
scalar.path=/scalar
scalar.pageTitle=API Biblioteca - Documentacion
scalar.theme=deepSpace
scalar.layout=modern
scalar.darkMode=true
scalar.showSidebar=true
